#!/usr/bin/env bash

msg="scripts added: audio/volume-norm"

# pull-n-merge
#git fetch origin && git merge --no-edit -m "[ci skip] merge with branch master"
git fetch && git pull

echo ########################### git status
git status
echo ########################### git diff
git diff
echo ########################### git add

# add all changed files
git add -A

# commit
git commit -m "$msg"

# git push origin master
git push
