#!/usr/bin/env bash

if [ ! -z "$*" ];then msg="$*"
else msg="default msg"
fi
git config user.name ikarus512 && git config user.email ikarus512@yandex.ru && git config core.editor mcedit
git pull
git add . && git commit -m "$msg" && git push
