#!/usr/bin/env bash
# USAGE
#    scripts commit message
#    scripts commit
#    scripts status
#    scripts pull
#    scripts diff

clear;clear; cd $HOME/w/m/scripts; echo "##### REPOSITORY: git clone https://github.com/ikarus512/scripts"

case "$1" in
commit)
    read -n1 -r -p "Are you surely want to commit/push the changes? [y/N] " response; echo
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        shift; msg="$*"; if [ -z "$msg" ]; then    read -r -p "Enter commit message: " msg; fi

        git config user.name ikarus512 && git config user.email ikarus512@yandex.ru && git config core.editor mcedit
        git pull || exit 1
        git add . && git commit -m "$msg" && git push
    else
        echo "User declined to commit/push the changes."
    fi
    #git update-index --chmod=+x file.sh
    ;;
*)  if [ "$*" != "" ]; then git $*; else echo "Nothing to do"; fi
    ;;
esac
