#!/usr/bin/env bash

## ubuntu 18

#sudo apt install -y isc-dhcp-server net-tools #ifconfig

ethName=$(ip -0 address show | perl -ne 'if (m#\d+:\s*(en\w*s0):#) { print $1; }')
macAddr1=$(ip -0 address show | grep -E "en\w*s0" -A 1 | perl -ne 'if (m#link\S*\s+(\S+)\s#) { print $1; }')
macAddr2="00:00:00:00:00:02"

d=/etc/network; f=interfaces; if [ ! -f $d/$f.old ]; then sudo cp $d/$f $d/$f.old; fi
if [ 1 = 0 ]; then
    sudo cp -frv $d/$f.old $d/$f
    cat $d/$f
else
    cp $d/$f.old etc-network-$f.old
    cat $d/$f.old | grep -v "$ethName"    >$f
    cat <<____EOF | perl -pe "s#ethName#$ethName#;" >>$f
auto  ethName
#iface ethName inet dhcp
iface ethName inet static
  address 5.5.5.15
  netmask 255.255.255.0
  broadcast 5.5.5.255
  gateway 5.5.5.1
____EOF
    sudo cp $f $d/$f
fi

sudo systemctl restart networking
