#!/usr/bin/env bash
## generate 10 ssec video and draw text on it
## http://ffmpeg.org/ffmpeg-filters.html#toc-drawtext-1
## http://ffmpeg.org/ffmpeg-filters.html#drawtext-1
rm -f test-output.mp4
ffmpeg -f lavfi -i testsrc=duration=10:size=854x480:rate=60 \
 -vf "drawtext=fontfile=/usr/share/fonts/truetype/freefont/FreeSerif.ttf:text=%{frame_num}:fontsize=72:r=60:x=(w-tw)/2: y=h-(2*lh):fontcolor=white:box=1:boxcolor=0x00000099" \
 test-output.mp4
