#!/usr/bin/env bash

# https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
# sudo add-apt-repository --remove ppa:mc3man/ffmpeg-test

sudo apt-get update -qq && sudo apt-get -y install \
  autoconf \
  automake \
  build-essential \
  cmake \
  git-core \
  libass-dev \
  libfreetype6-dev \
  libsdl2-dev \
  libtool \
  libva-dev \
  libvdpau-dev \
  libvorbis-dev \
  libxcb1-dev \
  libxcb-shm0-dev \
  libxcb-xfixes0-dev \
  nasm yasm \
  pkg-config \
  texinfo \
  wget \
  zlib1g-dev \
  libx264-dev libx265-dev libnuma-dev libvpx-dev libfdk-aac-dev libmp3lame-dev libopus-dev
  #libaom-dev
#exit

mkdir -p ~/ffmpeg_sources ~/ffmpeg_build
sudo echo
cd ~/ffmpeg_sources
wget -O master.zip https://github.com/georgmartius/vid.stab/archive/master.zip
unzip master.zip
cd vid.stab-master
#cmake -DCMAKE_INSTALL_PREFIX:PATH=~/ffmpeg_build .
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .
make
sudo make install
#export LD_LIBRRY_PATH=~/ffmpeg_build/lib:$LD_LIBRRY_PATH
#exit

mkdir -p ~/ffmpeg_sources ~/bin && \
cd ~/ffmpeg_sources && \
wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
tar xjvf ffmpeg-snapshot.tar.bz2 && \
cd ffmpeg && \
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --bindir="$HOME/bin" \
  --enable-gpl \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libvidstab \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree && \
PATH="$HOME/bin:$PATH" make && \
make install && \
hash -r
  # --enable-libaom
