#!/usr/bin/env bash

# https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
# sudo add-apt-repository --remove ppa:mc3man/ffmpeg-test

sudo apt-get update -qq && sudo apt-get -y install \
  autoconf \
  automake \
  build-essential \
  cmake \
  git-core \
  libass-dev \
  libfreetype6-dev \
  libsdl2-dev \
  libtool \
  libva-dev \
  libvdpau-dev \
  libvorbis-dev \
  libxcb1-dev \
  libxcb-shm0-dev \
  libxcb-xfixes0-dev \
  nasm yasm \
  pkg-config \
  texinfo \
  wget \
  zlib1g-dev \
  libx264-dev libx265-dev libnuma-dev libvpx-dev libfdk-aac-dev libmp3lame-dev libopus-dev
  #libaom-dev
#exit

SRC_DIR=$HOME/tmp/ffmpeg_sources
#DEST_DIR=$HOME/ffmpeg_build
DEST_DIR=/usr

mkdir -p $SRC_DIR $DEST_DIR
sudo echo
cd $SRC_DIR
wget -O master.zip https://github.com/georgmartius/vid.stab/archive/master.zip
unzip master.zip
cd vid.stab-master
cmake -DCMAKE_INSTALL_PREFIX:PATH=$DEST_DIR .
make
sudo make install
#export LD_LIBRRY_PATH=$DEST_DIR/lib:$LD_LIBRRY_PATH
#exit

mkdir -p $SRC_DIR $DEST_DIR/bin && \
cd $SRC_DIR && \
wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
tar xjvf ffmpeg-snapshot.tar.bz2 && \
cd ffmpeg && \
PATH="$DEST_DIR/bin:$PATH" PKG_CONFIG_PATH="$DEST_DIR/lib/pkgconfig" ./configure \
  --prefix="$DEST_DIR" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$DEST_DIR/include" \
  --extra-ldflags="-L$DEST_DIR/lib" \
  --extra-libs="-lpthread -lm" \
  --bindir="$DEST_DIR/bin" \
  --enable-gpl \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libvidstab \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree && \
PATH="$DEST_DIR/bin:$PATH" make && \
make install && \
hash -r
  # --enable-libaom
