#!/usr/bin/env bash
for f in $(ls *.mp3);do
    ### https://www.maketecheasier.com/normalize-music-files-with-ffmpeg
    #ffmpeg -i input.flac -filter:a "volume=0.5" output.fac
    #ffmpeg -i input.flac -filter:a "volume=1.5" output.fac
    #ffmpeg -i input.flac -filter:a "volume=5dB" output.flac
    #ffmpeg -i input.flac -filter:a "volume=-5dB" output.flac
    #ffmpeg -i $f -filter:a "volume=1.5" $f.mp3

    # normalize (lower peaks and raise valleys)
    ffmpeg -i $f -filter:a loudnorm $f.mp3


    ### https://www.ffmpeg.org/ffmpeg-filters.html#volumedetect
    # detect
    #ffmpeg -i $1 -filter:a volumedetect $1-1.mp3
done
