#!/usr/bin/env perl

#use POSIX qw(tzset);
#$ENV{TZ} = 'Europe/Moscow';
#tzset;
#print localtime;

#use POSIX qw(strftime);
#my $now_string = strftime "%a %b %e %H:%M:%S %Y", localtime;
#my $now_string = strftime "%a %b %e %H:%M:%S %Y", gmtime;

#bash:
#  date
#  TZ=Europe/Moscow date

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
printf("%04d%02d%02d_%02d%02d%02d", $year+1900,$mon+1,$mday,$hour,$min,$sec);
