#!/usr/bin/env bash
#sudo apt install -y tshark
#sudo wireshark -D    # list all interfaces

src=198.168.1.1
dst=198.168.1.2
port=25
interface=enp1s0
#filter="ip src host $src and ip dst host $dst and port $port"
filter="ip src host $src and ip dst host $dst"
when_start= # start capturing immediately
when_stop="-c 10" # stop after c packets
when_stop="-a duration:20" #after 20s
out="-w filename" # to file
out="-w -" # to screen
out_format="-T json" # pdml|ps|psml|json|jsonraw|ek|tabs|text|fields|?
f=$HOME/tshark1; echo >$f; chmod 777 $f

#sudo tshark -i $interface -f "$filter" $when_start $when_stop $out $out_format

#clear;clear;echo>$f; sudo tshark -i $interface -f "$filter" -w $f -T tabs -c 50
clear;clear;echo>$f; sudo tshark -i $interface -f "$filter" -w $f -T tabs -c 50


#sudo tshark -i - < $HOME/tmp/tshark1 >$HOME/tmp/tshark2
#sudo tshark -x -r $HOME/tmp/tshark1 >$HOME/tmp/tshark2










tshark: The capture session could not be initiated on interface 'enp1s0' (You don't have permission to capture on that device).
Please check to make sure you have sufficient permissions.

On Debian and Debian derivatives such as Ubuntu, if you have installed Wireshark from a package, try running
    sudo dpkg-reconfigure wireshark-common
selecting "<Yes>" in response to the question
    Should non-superusers be able to capture packets?
adding yourself to the "wireshark" group by running
    sudo usermod -a -G wireshark $USER
and then logging out and logging back in again.
0 packets captured
