#!/usr/bin/env bash

## ubuntu 18

#sudo apt install -y isc-dhcp-server net-tools #ifconfig

ethName=$(ip -0 address show | perl -ne 'if (m#\d+:\s*(en\w*s0):#) { print $1; }')
macAddr1=$(ip -0 address show | grep -E "en\w*s0" -A 1 | perl -ne 'if (m#link\S*\s+(\S+)\s#) { print $1; }')
macAddr2="00:00:00:00:00:02"

d=/etc/default; f=isc-dhcp-server; if [ ! -f $d/$f.old ]; then sudo cp $d/$f $d/$f.old; fi
cp $d/$f.old etc-default-$f.old
cat $d/$f.old | grep -v "INTERFACES"       >$f
#echo "INTERFACES=\"$ethName\""            >>$f
echo "INTERFACESv4=\"$ethName\""          >>$f
#echo "INTERFACESv6=\"$ethName\""          >>$f
#echo DHCPDv4_CONF=/etc/dhcp/dhcpd-my.conf >>$f
#echo DHCPDv4_PID=/var/run/dhcpd-my.pid    >>$f
sudo cp $f $d/$f

d=/etc/dhcp; f=dhcpd.conf; if [ ! -f $d/$f.old ]; then sudo cp $d/$f $d/$f.old; fi
cp $d/$f.old etc-dhcp-$f.old
cat $d/$f.old | grep -v "^$" | grep -v "^#"     >$f
cat <<EOF | perl -pe "s#macAddr1#$macAddr1#; s#macAddr2#$macAddr2#;" >> $f
### Define domain name, DHCP server IP address and gateway IP address
option domain-name "example.org";
option domain-name-servers ns1.example.org, ns2.example.org;
default-lease-time 600;
max-lease-time 7200;
#ddns-update-style none;
authoritative;
subnet 5.5.5.0 netmask 255.255.255.0 {
    option routers                  5.5.5.1;
    option broadcast-address        5.5.5.255;
    option subnet-mask              255.255.255.0;
    option domain-name              "example.org";
    option domain-search            "example.org";
    option domain-name-servers      5.5.5.2;
    range   5.5.5.10   5.5.5.100;
    range   5.5.5.110  5.5.5.254;
}
#host client1 {
#    hardware ethernet macAddr1;
#    fixed-address 5.5.5.15;
#    option host-name "client1.example.org";
#}
#host client2 {
#    hardware ethernet macAddr2;
#    fixed-address 5.5.5.52;
#    option host-name "client2.example.org";
#}
EOF
sudo cp $f $d/$f

#d=/etc/default; f=dhcpd.conf; if [ ! -f $d/$f.old ]; then sudo cp $d/$f $d/$f.old; fi
#cp $d/$f.old etc-default-$f.old
#cat $d/$f.old | grep -v "^$" | grep -v "^#"     >$f
#cat <<EOF | perl -pe "s#macAddr1#$macAddr1#; s#macAddr2#$macAddr2#;" >> $f
#### Define domain name, DHCP server IP address and gateway IP address
#EOF
#sudo cp $f $d/$f
