#!/usr/bin/env bash
#ffmpeg -i in.avi -ss 00:01:00 -to 00:02:00 -target pal-svcd out.avi

in=$1
out=out.mp3
s=(00:00:00 00:01:00 00:20:00 00:21:00)
opts=
opts="$opts -strict -2" ## in case of experimental codec aac
opts="$opts -acodec copy -vcodec copy"
##opts="$opts -target pal-svcd"

clear
sz=${#s[@]}
for i in $(seq 1 $((sz - 1)) );do
    start=${s[i-1]}
    end=${s[i]}
    name="${out%.*}"
    ext="${out##*.}"
    ffmpeg -i $in -ss $start -to $end $opts  $name-$i.$ext
done
