#!/usr/bin/env bash

ff=1.htm
echo "Creating $ff..."
echo >$ff

for f in $(ls p*.png); do
    echo "--- convert $f to c$f..."
    mogrify -unsharp 0.25x0.25+8+0.065 -resize 800x -normalize -density 180 *.png  # resize sharp
done

for f in $(ls c*.png); do

node -e "
var fs = require('fs');

// function to encode file data to base64 encoded string
function base64_encode(file) {
    // read binary data
    var bitmap = fs.readFileSync(file);
    // convert binary data to base64 encoded string
    return new Buffer(bitmap).toString('base64');
}

// function to create file from base64 encoded string
function base64_decode(base64str, file) {
    // create buffer object from base64 encoded string, it is important to tell the constructor that the string is base64 encoded
    var bitmap = new Buffer(base64str, 'base64');
    // write buffer to file
    fs.writeFileSync(file, bitmap);
    console.log('******** File created from base64 encoded string ********');
}

// convert image to base64 encoded string
var base64str = base64_encode(\"$f\");
console.log('<img src=\"data:image/png;base64,' + base64str + '\" alt=\"$f\" /><br/>');
// convert base64 string back to image 
//base64_decode(base64str, 'copy.jpg');
" >>$ff

done

#<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
#    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
#        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" /><br/>
